#ifndef __LOCA_H__
#define __LOCA_H__

extern char *FleetNames[14];
extern char *DefenseNames[8];
extern char *FleetShort[14];
extern char *DefenseShort[8];
extern char *SlotCaption[2];

enum {
    LOCA084_BATTLE_REPORT = 0,
    LOCA084_DATE_TIME,
    LOCA084_ENCOUNTER,
    LOCA084_TECHS,
    LOCA084_SLOT_TYPE,
    LOCA084_SLOT_AMOUNT,
    LOCA084_SLOT_WEAP,
    LOCA084_SLOT_SHLD,
    LOCA084_SLOT_HULL,
    LOCA084_SLOT_DESTROYED,
    LOCA084_ASHOOT,
    LOCA084_DSHOOT,
    LOCA084_AWON,
    LOCA084_DWON,
    LOCA084_DRAW,
    LOCA084_PLUNDER,
    LOCA084_LOSSTATS,
    LOCA084_DEBRIS,
    LOCA084_MOONCHANCE,
    LOCA084_REPAIRED,
    
    LOCARED_BATTLE_REPORT,
    LOCARED_DATE_TIME,
    LOCARED_ENCOUNTER,
    LOCARED_TECHS,
    LOCARED_SLOT_TYPE,
    LOCARED_SLOT_AMOUNT,
    LOCARED_SLOT_WEAP,
    LOCARED_SLOT_SHLD,
    LOCARED_SLOT_HULL,
    LOCARED_SLOT_DESTROYED,
    LOCARED_ASHOOT,
    LOCARED_DSHOOT,
    LOCARED_AWON,
    LOCARED_DWON,
    LOCARED_DRAW,
    LOCARED_PLUNDER,
    LOCARED_LOSSTATS,
    LOCARED_DEBRIS,
    LOCARED_MOONCHANCE,
    LOCARED_REPAIRED,

    LOCD_SIMARG,
    LOCD_NOBATTLE,
    LOCD_REPAIR,

    LOCA_MAX,
};

extern  char *loca[];

void InitLoca (char *lang);

#endif  // __LOCA_H__